name: Keep Replit Awake

# 定时任务
on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次

jobs:
  ping_replit:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping to Replit
        run: curl -X GET https://f9dac645-107c-4c04-a2ae-3b466ee181ae-00-1wr4htipi5j86.worf.replit.dev/
